Repository LEEJESEOK/KOSA-Final, pull requests merged in 2022-06, with the labels that each got.

#4 [KF-33] Spring XSS설정 및 POM.XML 수정
  pom.xml
  src/main/java/com/hyundai/kosafinal/config/XssConfig.java
  src/main/resources/lucy-xss-servlet-filter-rule.xml
  src/main/resources/lucy-xss-superset-sax.xml
Labels: bug, 초기 설정

#5 fixed: XSS 의존성 버전 변경
  pom.xml
Labels: bug

#8 KF-37 - KF-37-dto-패키지-수정
  src/main/java/com/hyundai/kosafinal/domain/CartDTO.java
  src/main/java/com/hyundai/kosafinal/domain/CategoryDTO.java
  src/main/java/com/hyundai/kosafinal/domain/ColorDTO.java
  src/main/java/com/hyundai/kosafinal/domain/GradeDTO.java
  src/main/java/com/hyundai/kosafinal/domain/MypageReviewDTO.java
  src/main/java/com/hyundai/kosafinal/domain/OrderItemDTO.java
  src/main/java/com/hyundai/kosafinal/domain/OrderedListDTO.java
  src/main/java/com/hyundai/kosafinal/domain/ProductDTO.java
  src/main/java/com/hyundai/kosafinal/domain/ProductReviewDTO.java
  src/main/java/com/hyundai/kosafinal/domain/ReplyDTO.java
  src/main/java/com/hyundai/kosafinal/domain/RoleSetDTO.java
  src/main/java/com/hyundai/kosafinal/domain/UserDTO.java
Labels: bug

#9 KF-37 - KF-37-클래스명-DTO-추가
  src/main/java/com/hyundai/kosafinal/domain/CartDTO.java
  src/main/java/com/hyundai/kosafinal/domain/CategoryDTO.java
  src/main/java/com/hyundai/kosafinal/domain/ColorDTO.java
  src/main/java/com/hyundai/kosafinal/domain/GradeDTO.java
  src/main/java/com/hyundai/kosafinal/domain/MypageReviewDTO.java
  src/main/java/com/hyundai/kosafinal/domain/OrderItemDTO.java
  src/main/java/com/hyundai/kosafinal/domain/OrderedListDTO.java
  src/main/java/com/hyundai/kosafinal/domain/ProductDTO.java
  src/main/java/com/hyundai/kosafinal/domain/ProductReviewDTO.java
  src/main/java/com/hyundai/kosafinal/domain/ReplyDTO.java
  src/main/java/com/hyundai/kosafinal/domain/UserDTO.java
Labels: bug

#10 [KF-35] DB 분리 작업
  .gitignore
  src/main/java/com/hyundai/kosafinal/config/ProductDatabaseConfig.java
  src/main/java/com/hyundai/kosafinal/config/UserOrderDatabaseConfig.java
  src/main/java/com/hyundai/kosafinal/mapper/product/ProductMapper.java
  src/main/java/com/hyundai/kosafinal/mapper/userorder/UserOrderMapper.java
  src/main/resources/application.properties
  src/main/resources/mybatis/mapper-config.xml
  src/main/resources/mybatis/mapper/product/ProductMapper.xml
  src/main/resources/mybatis/mapper/userorder/UserOrderMapper.xml
  src/test/java/com/hyundai/kosafinal/dbTest/DataSourceTests.java
Labels: 초기 설정
